telnet/telnet.c

[update]add FINSH_USING_MSH define

---

iperf/iperf.c

【修改】：介绍中多余的符号

---

ntp/ntp.c

【删除】ntp 功能 select 依赖

---

iperf/iperf.c

【修改】修复变量值溢出导致计算出错的问题

---

iperf/iperf.c

【修改】修复 iperf server 模式无法关闭的问题

---

telnet/telnet.c

增加对设备的OPS的支持

---

ping/ping.c

【修改】适配 LWIP 开启硬件校验和的情况

---

tftp/tftp_port.c

【修改】添加 tcpip 线程栈大小检查

---

ntp/ntp.c

【修改】NTP 发送数据格式

---

ntp/ntp.c

【修改】check 数据赋值方式

---

iperf/iperf.c

[fix] malloc conflict problem
Signed-off-by: MurphyZhao <d2014zjt@163.com>

[fix] malloc conflict problem

---

tcpdump/tcpdump.c

新添加功能：
1. 添加zero包定位0点时间
修复问题：
1. 修复当包len=0时无法抓包的问题
2. 修复抓包时间戳将ms当场us处理的问题
3. 修复包时间戳获取不准确的问题

【更新】更新抓包工具

---

ntp/ntp.h

[
修复 NTP API 在 C++ 文件中调用时，出现的编译报错。
]
以下的内容不应该在提交PR时的message修改，修改下述message，PR会被直接关闭。请在提交PR后，浏览器查看PR并对以下检查项逐项check，没问题后逐条在页面上打钩。
The following content must not be changed in submitted PR message. Otherwise, the PR will be closed immediately. After submitted PR, please use web browser to visit PR, and check items one by one, and ticked them if no problem.
必须选择一项 Choose one (Mandatory):
我在这个拉取/合并请求中已经考虑了 As part of this pull request, I've considered the following:

C++ support

---

tftp/tftp.h
tftp/tftp_client.c
tftp/tftp_xfer.c

完善客户端文件传输请求

---

iperf/iperf.c

[update] iperf support mutli-thread test.
[update] float data change into integer, but look likes decimals.

[update] iperf support mutli-thread test.

---

ntp/README.md
ntp/ntp.c

[ntp]增加NTP_USING_AUTO_SYNC功能
重命名RTC_NTP_FIRST_SYNC_DELAY RTC_NTP_SYNC_PERIOD
完善readme

[ntp]增加NTP_USING_AUTO_SYNC功能

---

ntp/ntp.c

https://github.com/RT-Thread-packages/netutils/issues/69

修复4.0.3版本里不能设置日期的bug

---

ping/ping.c
tcpdump/tcpdump.c
telnet/telnet.c
tftp/tftp.h
tftp/tftp_client.c
tftp/tftp_port.c
tftp/tftp_server.c
tftp/tftp_xfer.c
tftp/tftp_xfer.h

 优化代码 将GPL改为Apache协议

---

ping/ping.c
tcpdump/tcpdump.c
telnet/telnet.c
tftp/tftp_port.c

匹配至RT-Thread 4.1.0

---

iperf/iperf.c

- Fixed compiling error when enabling LOG with rt-thread 5.0

Fix compiling error with rtt-5.0

---

iperf/iperf.c

add udp client's log

---

telnet/telnet.c

开启telnet的回显选项，可以使用table键、上下键等

---

telnet/telnet.c

修复了telnet echo option，也就是回显功能，在debian telnet和busybox telnet下测试通过

[telnet] 修复echo option

---

telnet/telnet.c

在5.1.0下，打开RT_USING_POSIX_STDIO下测试通过，需配合finsh改动使用，https://github.com/RT-Thread/rt-thread/pull/9581

[telnet]修复5.1.0下RT_USING_POSIX_STDIO打开后的编译和使用

---

tcpdump/tcpdump.c

fixed: https://github.com/RT-Thread/rt-thread/issues/10446

fix complier problem under the strict mode
